"""
CecilIA v2 — Sistema de IA para Control Fiscal
Contraloria General de la Republica de Colombia

Archivo: app/auth/roles.py
Proposito: Definicion completa de los 8 roles del sistema con sus permisos,
           modulos habilitados y acciones rapidas
Sprint: 0
Autor: Equipo Tecnico CecilIA — CD-TIC-CGR
Fecha: Abril 2026
"""

from typing import Any

# ── Definicion de roles del sistema CecilIA v2 ───────────────────────────────
# Cada rol define:
#   - permisos: lista de acciones permitidas en el sistema
#   - puede_ver: colecciones RAG y tipos de datos visibles
#   - modulos: modulos de la interfaz habilitados
#   - acciones_rapidas: acciones predefinidas en la barra de acciones rapidas

ROLES: dict[str, dict[str, Any]] = {
    "auditor_des": {
        "descripcion": "Auditor de la Direccion de Estudios Sectoriales",
        "permisos": [
            "chat",
            "rag_consultar",
            "documentos_cargar",
            "documentos_ver",
            "hallazgos_crear",
            "hallazgos_editar",
            "hallazgos_ver",
            "formatos_generar",
            "formatos_ver",
            "auditoria_ver",
            "proyecto_crear",
            "proyecto_editar",
        ],
        "puede_ver": [
            "normativo",
            "institucional",
            "academico",
            "tecnico_tic",
            "estadistico",
            "jurisprudencial",
            "auditoria",
        ],
        "modulos": [
            "chat",
            "documentos",
            "hallazgos",
            "formatos",
            "auditoria",
        ],
        "acciones_rapidas": [
            "Consultar normativa vigente",
            "Estructurar hallazgo",
            "Generar formato CGR",
            "Analizar riesgo sectorial",
            "Buscar jurisprudencia",
        ],
    },
    "auditor_dvf": {
        "descripcion": "Auditor de la Direccion de Vigilancia Fiscal",
        "permisos": [
            "chat",
            "rag_consultar",
            "documentos_cargar",
            "documentos_ver",
            "hallazgos_crear",
            "hallazgos_editar",
            "hallazgos_ver",
            "formatos_generar",
            "formatos_ver",
            "auditoria_ver",
            "proyecto_crear",
            "proyecto_editar",
        ],
        "puede_ver": [
            "normativo",
            "institucional",
            "academico",
            "tecnico_tic",
            "estadistico",
            "jurisprudencial",
            "auditoria",
        ],
        "modulos": [
            "chat",
            "documentos",
            "hallazgos",
            "formatos",
            "auditoria",
        ],
        "acciones_rapidas": [
            "Consultar normativa vigente",
            "Estructurar hallazgo",
            "Generar formato CGR",
            "Verificar presupuesto entidad",
            "Buscar jurisprudencia",
        ],
    },
    "profesional_des": {
        "descripcion": "Profesional de apoyo de la Direccion de Estudios Sectoriales",
        "permisos": [
            "chat",
            "rag_consultar",
            "documentos_ver",
            "hallazgos_ver",
            "formatos_ver",
            "auditoria_ver",
        ],
        "puede_ver": [
            "normativo",
            "institucional",
            "academico",
            "estadistico",
        ],
        "modulos": [
            "chat",
            "documentos",
            "hallazgos",
            "auditoria",
        ],
        "acciones_rapidas": [
            "Consultar normativa vigente",
            "Buscar estadisticas sectoriales",
            "Consultar guia de auditoria",
        ],
    },
    "profesional_dvf": {
        "descripcion": "Profesional de apoyo de la Direccion de Vigilancia Fiscal",
        "permisos": [
            "chat",
            "rag_consultar",
            "documentos_ver",
            "hallazgos_ver",
            "formatos_ver",
            "auditoria_ver",
        ],
        "puede_ver": [
            "normativo",
            "institucional",
            "academico",
            "estadistico",
        ],
        "modulos": [
            "chat",
            "documentos",
            "hallazgos",
            "auditoria",
        ],
        "acciones_rapidas": [
            "Consultar normativa vigente",
            "Buscar estadisticas sectoriales",
            "Consultar guia de auditoria",
        ],
    },
    "director_des": {
        "descripcion": "Director de la Direccion de Estudios Sectoriales",
        "permisos": [
            "chat",
            "rag_consultar",
            "documentos_cargar",
            "documentos_ver",
            "hallazgos_crear",
            "hallazgos_editar",
            "hallazgos_ver",
            "hallazgos_aprobar",
            "formatos_generar",
            "formatos_ver",
            "formatos_aprobar",
            "auditoria_ver",
            "auditoria_crear",
            "auditoria_editar",
            "proyecto_crear",
            "proyecto_editar",
            "analitica_ver",
            "observatorio_ver",
        ],
        "puede_ver": [
            "normativo",
            "institucional",
            "academico",
            "tecnico_tic",
            "estadistico",
            "jurisprudencial",
            "auditoria",
        ],
        "modulos": [
            "chat",
            "documentos",
            "hallazgos",
            "formatos",
            "auditoria",
            "analitica",
            "observatorio",
        ],
        "acciones_rapidas": [
            "Ver resumen de auditorias DES",
            "Aprobar hallazgos pendientes",
            "Consultar indicadores sectoriales",
            "Generar informe de avance",
            "Ver alertas observatorio",
        ],
    },
    "director_dvf": {
        "descripcion": "Director de la Direccion de Vigilancia Fiscal",
        "permisos": [
            "chat",
            "rag_consultar",
            "documentos_cargar",
            "documentos_ver",
            "hallazgos_crear",
            "hallazgos_editar",
            "hallazgos_ver",
            "hallazgos_aprobar",
            "formatos_generar",
            "formatos_ver",
            "formatos_aprobar",
            "auditoria_ver",
            "auditoria_crear",
            "auditoria_editar",
            "proyecto_crear",
            "proyecto_editar",
            "analitica_ver",
            "observatorio_ver",
        ],
        "puede_ver": [
            "normativo",
            "institucional",
            "academico",
            "tecnico_tic",
            "estadistico",
            "jurisprudencial",
            "auditoria",
        ],
        "modulos": [
            "chat",
            "documentos",
            "hallazgos",
            "formatos",
            "auditoria",
            "analitica",
            "observatorio",
        ],
        "acciones_rapidas": [
            "Ver resumen de auditorias DVF",
            "Aprobar hallazgos pendientes",
            "Consultar indicadores fiscales",
            "Generar informe de avance",
            "Ver alertas observatorio",
        ],
    },
    "admin_tic": {
        "descripcion": "Administrador TIC del Centro de Datos — CD-TIC-CGR",
        "permisos": [
            "chat",
            "rag_consultar",
            "rag_administrar",
            "documentos_cargar",
            "documentos_ver",
            "documentos_eliminar",
            "hallazgos_ver",
            "formatos_ver",
            "auditoria_ver",
            "analitica_ver",
            "analitica_administrar",
            "observatorio_ver",
            "observatorio_administrar",
            "usuarios_ver",
            "usuarios_crear",
            "usuarios_editar",
            "usuarios_desactivar",
            "sistema_configurar",
            "logs_ver",
        ],
        "puede_ver": [
            "normativo",
            "institucional",
            "academico",
            "tecnico_tic",
            "estadistico",
            "jurisprudencial",
            "auditoria",
        ],
        "modulos": [
            "chat",
            "documentos",
            "hallazgos",
            "formatos",
            "auditoria",
            "analitica",
            "observatorio",
            "administracion",
            "logs",
        ],
        "acciones_rapidas": [
            "Ver estado del sistema",
            "Administrar colecciones RAG",
            "Gestionar usuarios",
            "Ver logs de trazabilidad",
            "Configurar modelos LLM",
        ],
    },
    "observatorio": {
        "descripcion": "Analista del Observatorio de Control Fiscal",
        "permisos": [
            "chat",
            "rag_consultar",
            "documentos_ver",
            "observatorio_ver",
            "observatorio_alertas_crear",
            "observatorio_alertas_editar",
            "analitica_ver",
        ],
        "puede_ver": [
            "normativo",
            "institucional",
            "estadistico",
            "auditoria",
        ],
        "modulos": [
            "chat",
            "documentos",
            "observatorio",
            "analitica",
        ],
        "acciones_rapidas": [
            "Ver alertas activas",
            "Crear nueva alerta",
            "Consultar indicadores macroeconomicos",
            "Analizar tendencias sectoriales",
            "Generar reporte observatorio",
        ],
    },
}
